# Generated by Django 4.1.2 on 2022-12-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tagged_company',
            field=models.ManyToManyField(blank=True, related_name='tagCompany', to='myNewsApp.company'),
        ),
    ]
